files:
  - source: /docs/source/**/*.rst
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
  - source: /**/README
    ignore:
      - '*.md'
    translation: /%original_path%/%file_name%_%two_letters_code%
  - source: /**/*.md
    translation: /%original_path%/%file_name%_%two_letters_code%.md
  - source: /COPYING.rst
    translation: /%file_name%_%two_letters_code%.rst
  - source: /**/*.txt
    translation: /%original_path%/%file_name%_%two_letters_code%.txt
